name: Java CI with Maven

on:
  push:
    branches:
      - master
      - issue-*

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: maven
    - name: Run tests 
        run: mvn clean 
    - name: Build with Maven and run tests
        run: mvn clean install
